--liquibase formatted sql
--changeset SergeN:tablesV1

CREATE SCHEMA IF NOT EXISTS certificate;

CREATE TABLE certificate.Department (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE certificate.Users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) NOT NULL UNIQUE,
    user_index VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    department_id BIGINT NOT NULL,
    plant VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_department FOREIGN KEY (department_id) REFERENCES certificate.Department(id)
);

CREATE TABLE certificate.Certificate (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(255) NOT NULL,
    valid_from TIMESTAMP NOT NULL,
    valid_to TIMESTAMP NOT NULL,
    supplier_id BIGINT NOT NULL,
    file_data OID,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE certificate.assigned_users (
    certificate_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_certificate FOREIGN KEY (certificate_id) REFERENCES certificate.Certificate(id),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES certificate.Users(id)
);


CREATE TABLE certificate.Supplier (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    supplier_index VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE certificate.Certificate
    ADD CONSTRAINT fk_supplier FOREIGN KEY (supplier_id) REFERENCES certificate.Supplier(id);

CREATE TABLE certificate.Comment (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    certificate_id BIGINT NOT NULL,
    comment TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES certificate.Users(id),
    CONSTRAINT fk_certificate FOREIGN KEY (certificate_id) REFERENCES certificate.Certificate(id)
);